demo_tuple1=("Melborne","Sydney","France","Delhi","France")
demo_tuple2=(True,False,True,"3",20.4,"10","Washinton")
print(len(demo_tuple1))
print(type(demo_tuple2))
print(demo_tuple1.count("France"))
print(demo_tuple2.index(20.4))
print(demo_tuple1[2])
print(demo_tuple2[1:3])
